export const SIGN_IN_LOADING = 'SIGN_IN_LOADING'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR'

export const SIGN_OUT_LOADING = 'SIGN_OUT_LOADING'
export const SIGN_OUT = 'SIGN_OUT'

export const SIGN_UP_LOADING = 'SIGN_UP_LOADING'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR'

export const DATA_LOADING = 'DATA_LOADING'
export const DATA_SUCCESS = 'DATA_SUCCESS'
export const DATA_ERROR = 'DATA_ERROR'

export const NEW_DATA_LOADING = 'NEW_DATA_LOADING'
export const NEW_DATA_SUCCESS = 'NEW_DATA_SUCCESS'
export const NEW_DATA_ERROR = 'NEW_DATA_ERROR'
export const NEW_DATA_STATE = 'NEW_DATA_STATE'

export const DELETE_DATA_LOADING = 'DELETE_DATA_LOADING'
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS'
export const DELETE_DATA_ERROR = 'DELETE_DATA_ERROR'

export const EDIT_DATA_STATE = 'EDIT_DATA_STATE'
export const EDIT_DATA_LOADING = 'EDIT_DATA_LOADING'
export const EDIT_DATA_SUCCESS = 'EDIT_DATA_SUCCESS'
export const EDIT_DATA_ERROR = 'EDIT_DATA_ERROR'

export const MARK_DATA_STATE = 'MARK_DATA_STATE'
export const MARK_DATA_LOADING = 'MARK_DATA_LOADING'
export const MARK_DATA_SUCCESS = 'MARK_DATA_SUCCESS'
export const MARK_DATA_ERROR = 'MARK_DATA_ERROR'